tailwind.config = {
    darkMode: "class",
    theme: {
        extend: {
            "colors": {
                "on-primary-fixed": "#001b3d",
                "on-primary-container": "#83aef5",
                "surface-dim": "#dcd9d9",
                "secondary-container": "#fecb00",
                "outline": "#737781",
                "on-secondary": "#ffffff",
                "surface-container-lowest": "#ffffff",
                "tertiary": "#4c1d00",
                "tertiary-fixed": "#ffdbcb",
                "on-secondary-fixed": "#241a00",
                "surface-container-low": "#f6f3f2",
                "on-tertiary": "#ffffff",
                "primary-fixed": "#d6e3ff",
                "outline-variant": "#c3c6d2",
                "inverse-surface": "#303030",
                "secondary-fixed": "#ffe08b",
                "surface-tint": "#305ea0",
                "surface-container-high": "#eae8e7",
                "background": "#fbf9f8",
                "on-secondary-fixed-variant": "#584400",
                "on-surface": "#1b1c1c",
                "surface-container": "#f0eded",
                "on-error-container": "#93000a",
                "inverse-on-surface": "#f3f0f0",
                "on-secondary-container": "#6e5700",
                "error-container": "#ffdad6",
                "surface-white": "#FFFFFF",
                "surface": "#fbf9f8",
                "on-background": "#1b1c1c",
                "on-tertiary-fixed": "#341100",
                "on-error": "#ffffff",
                "primary-container": "#004080",
                "error": "#ba1a1a",
                "inverse-primary": "#a9c7ff",
                "secondary": "#745b00",
                "on-primary-fixed-variant": "#0e4686",
                "on-tertiary-container": "#f59561",
                "on-primary": "#ffffff",
                "primary": "#002a58",
                "tertiary-container": "#6f2d00",
                "primary-fixed-dim": "#a9c7ff",
                "info-blue": "#2D95E3",
                "border-light": "#DEE2E6",
                "tertiary-fixed-dim": "#ffb691",
                "surface-bright": "#fbf9f8",
                "surface-variant": "#e4e2e1",
                "surface-subtle": "#F8F9FA",
                "secondary-fixed-dim": "#f1c100"
            },
            "borderRadius": {
                "DEFAULT": "0.25rem",
                "lg": "0.5rem",
                "xl": "0.75rem",
                "full": "9999px"
            },
            "spacing": {
                "margin-mobile": "16px",
                "section-padding": "64px",
                "stack-md": "16px",
                "gutter": "24px",
                "margin-desktop": "32px",
                "stack-lg": "32px",
                "container-max": "1200px",
                "stack-sm": "8px"
            },
            "fontFamily": {
                "label-sm": ["Inter"],
                "body-md": ["Inter"],
                "headline-lg-mobile": ["Inter"],
                "headline-md": ["Inter"],
                "display-lg-mobile": ["Inter"],
                "body-lg": ["Inter"],
                "headline-lg": ["Inter"],
                "label-md": ["Inter"],
                "display-lg": ["Inter"]
            },
            "fontSize": {
                "label-sm": ["12px", { "lineHeight": "16px", "letterSpacing": "0.02em", "fontWeight": "500" }],
                "body-md": ["16px", { "lineHeight": "26px", "fontWeight": "400" }],
                "headline-lg-mobile": ["28px", { "lineHeight": "36px", "fontWeight": "700" }],
                "headline-md": ["24px", { "lineHeight": "32px", "fontWeight": "600" }],
                "display-lg-mobile": ["36px", { "lineHeight": "44px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
                "body-lg": ["18px", { "lineHeight": "30px", "fontWeight": "400" }],
                "headline-lg": ["32px", { "lineHeight": "40px", "fontWeight": "700" }],
                "label-md": ["14px", { "lineHeight": "20px", "letterSpacing": "0.01em", "fontWeight": "600" }],
                "display-lg": ["48px", { "lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "700" }]
            }
        },
    },
}
